require:
  - rubocop-performance

Bundler/OrderedGems:
  Enabled: false

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/EmptyLinesAroundAccessModifier:
  EnforcedStyle: only_before

Layout/LineLength:
  Max: 200

Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: space

Metrics/BlockLength:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: false

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Style/ConditionalAssignment:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Max: 25

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/AndOr:
  Enabled: false
