require:
  - rubocop-performance

Bundler/OrderedGems:
  Enabled: false

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/EmptyLinesAroundAccessModifier:
  EnforcedStyle: only_before

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Max: 200

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: space

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Max: 150

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Max: 25

Metrics/ParameterLists:
  CountKeywordArgs: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Naming/InclusiveLanguage:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/IfWithBooleanLiteralBranches:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/QuotedSymbols:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false
